/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'user' at '9/23/16 3:16 PM' with Gradle 2.14.1
 *
 * @author user, @date 9/23/16 3:16 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
